language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m"
install:
  - mvn -v
before_script:
  - psql -U postgres -f travis/postgresql.sql
script: mvn -U -Ptravis clean package
